version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: Install dockerize
          command: |
            # sampled from CircleCI's images
            # See https://github.com/CircleCI-Public/cimg-base/blob/204a4822173265dba9a43d4aca6386ad7d76f793/Dockerfile.template#L32-L36
            sudo curl -sSL --fail --retry 3 --output /tmp/dockerize-linux-amd64.tar.gz "https://circle-downloads.s3.amazonaws.com/circleci-images/cache/linux-amd64/dockerize-latest.tar.gz"
            sudo tar -C /usr/local/bin -xzvf /tmp/dockerize-linux-amd64.tar.gz
            sudo rm -rf /tmp/dockerize-linux-amd64.tar.gz
            # Quick test of Dockerize
            dockerize --version
      - run:
          name: Run Nginx server in background (available at port 8080)
          command: |
            run --name nginx -p "8080:80" nginx
      - run:
          name: Wait for Nginx to be ready
          command: |
            dockerize -wait http://localhost:8080 -timeout 20s
      - run:
          name: Start integration tests
          command: |
            echo "TODO!"

workflows:
  main:
    jobs:
      - test
